/**
 * Path Narrator — builds natural-language descriptions from pathfinding results.
 *
 * Layer: Application (presentation helper)
 * Purpose: Converts pathfinding narration hints + terrain data into human-readable
 *          descriptions for combat events and CLI display.
 */

import type { Position } from "../../../../domain/rules/movement.js";

/**
 * Input for building path narration.
 */
export interface PathNarrationInput {
  /** Actor display name */
  actorName: string;
  /** Target display name (if moving toward someone) */
  targetName?: string;
  /** The path cells traversed */
  pathCells?: Position[];
  /** Total movement cost in feet */
  pathCostFeet?: number;
  /** Desired range to target (e.g., 5 for melee) */
  desiredRange?: number;
  /** Hints generated by the A* pathfinder */
  narrationHints?: string[];
  /** Whether the move was partial (couldn't reach destination) */
  partial?: boolean;
  /** Actor's start position (for cardinal direction) */
  startPosition?: Position;
  /** Final destination position (for cardinal direction) */
  endPosition?: Position;
}

/**
 * Compute the primary cardinal/intercardinal direction from one position to another.
 */
function getCardinalDirection(from: Position, to: Position): string {
  const dx = to.x - from.x;
  const dy = to.y - from.y;

  if (dx === 0 && dy === 0) return "";

  // Use atan2 to get angle; note: positive y is south in grid coords
  const angle = Math.atan2(dy, dx) * (180 / Math.PI);

  // Map angle to 8-point compass (0° = east)
  if (angle >= -22.5 && angle < 22.5) return "east";
  if (angle >= 22.5 && angle < 67.5) return "southeast";
  if (angle >= 67.5 && angle < 112.5) return "south";
  if (angle >= 112.5 && angle < 157.5) return "southwest";
  if (angle >= 157.5 || angle < -157.5) return "west";
  if (angle >= -157.5 && angle < -112.5) return "northwest";
  if (angle >= -112.5 && angle < -67.5) return "north";
  if (angle >= -67.5 && angle < -22.5) return "northeast";

  return "";
}

/**
 * Choose a movement verb based on distance covered relative to speed.
 * Adds flavour without changing mechanics.
 */
function chooseMovementVerb(costFeet: number | undefined): string {
  if (costFeet == null) return "moves";
  if (costFeet >= 25) return "rushes";
  if (costFeet <= 5) return "steps";
  return "moves";
}

/**
 * Build a human-readable narration of a pathfinding move.
 *
 * Examples:
 * - "Goblin rushes 30ft east toward Brave Fighter."
 * - "Brave Fighter moves 25ft toward Goblin, but can't reach the destination. Crossing difficult terrain — movement slowed."
 * - "Brave Fighter steps 5ft south toward Dragon."
 */
export function buildPathNarration(input: PathNarrationInput): string {
  const { actorName, targetName, pathCostFeet, pathCells, narrationHints, partial, startPosition, endPosition } = input;

  const parts: string[] = [];

  // Determine movement verb and direction
  const verb = chooseMovementVerb(pathCostFeet);
  const distDesc = pathCostFeet != null ? `${pathCostFeet}ft` : "";

  // Compute cardinal direction from start/end positions or first/last path cells
  let direction = "";
  const from = startPosition ?? (pathCells && pathCells.length >= 2 ? pathCells[0] : undefined);
  const to = endPosition ?? (pathCells && pathCells.length >= 2 ? pathCells[pathCells.length - 1] : undefined);
  if (from && to) {
    direction = getCardinalDirection(from, to);
  }

  const dirSuffix = direction ? ` ${direction}` : "";

  // Core movement description
  if (targetName) {
    if (distDesc) {
      parts.push(`${actorName} ${verb} ${distDesc}${dirSuffix} toward ${targetName}`);
    } else {
      parts.push(`${actorName} ${verb}${dirSuffix} toward ${targetName}`);
    }
  } else {
    if (distDesc) {
      parts.push(`${actorName} ${verb} ${distDesc}${dirSuffix}`);
    } else {
      parts.push(`${actorName} ${verb}${dirSuffix}`);
    }
  }

  // Append partial-move note
  if (partial) {
    parts.push("but can't reach the destination");
  }

  // Join the base sentence
  let narration = parts.join(", ") + ".";

  // Append terrain/detour hints as separate sentences
  if (narrationHints && narrationHints.length > 0) {
    // Deduplicate and capitalize
    const unique = [...new Set(narrationHints)];
    for (const hint of unique) {
      // Capitalize first letter if not already
      const capitalized = hint.charAt(0).toUpperCase() + hint.slice(1);
      // Ensure ends with period
      const formatted = capitalized.endsWith(".") || capitalized.endsWith("!") || capitalized.endsWith("—")
        ? capitalized
        : capitalized + ".";
      narration += " " + formatted;
    }
  }

  return narration;
}
