/**
 * Battle Plan type definitions for faction-level tactical planning.
 *
 * Layer: Application
 * Purpose: Define structured battle plans that give AI combatants
 * multi-turn strategic context and faction coordination.
 */

/**
 * A faction-level battle plan generated by LLM at the start of combat
 * or when re-planning triggers fire.
 */
export interface BattlePlan {
  /** Faction this plan belongs to (e.g., "enemy", "party"). */
  faction: string;
  /** Combat round when this plan was generated. */
  generatedAtRound: number;
  /** Overall tactical priority. */
  priority: "offensive" | "defensive" | "retreat" | "protect" | "ambush";
  /** Primary target name to focus on (if any). */
  focusTarget?: string;
  /** Map of creature name → role description. */
  creatureRoles: Record<string, string>;
  /** Free-form 1-2 sentence strategy summary. */
  tacticalNotes: string;
  /** Descriptive condition for when the faction should retreat. */
  retreatCondition?: string;

  // ──────────────────────────────────────────────────────────────────────────
  // Battlefield snapshot captured at plan-generation time.
  // Used by shouldReplan() heuristics — all fields are optional for backward
  // compatibility with plans stored before this feature was added.
  // ──────────────────────────────────────────────────────────────────────────

  /** Map of combatantId → hpCurrent at the moment this plan was generated. */
  allyHpAtGeneration?: Record<string, number>;
  /** IDs of living ally combatants at the moment this plan was generated. */
  livingAllyIdsAtGeneration?: string[];
  /** IDs of living enemy combatants at the moment this plan was generated. */
  livingEnemyIdsAtGeneration?: string[];
}

/**
 * The view of a battle plan that an individual combatant receives.
 * Each creature sees the overall strategy but only its own role.
 */
export interface CombatantBattlePlanView {
  /** Overall faction priority. */
  priority: string;
  /** Primary target name to focus on. */
  focusTarget?: string;
  /** This creature's specific role in the plan. */
  yourRole?: string;
  /** General tactical guidance. */
  tacticalNotes: string;
  /** When to abandon the plan and retreat. */
  retreatCondition?: string;
}
